version: "3.9"
services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
      - api
      - pocketbase

  web:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.web
    container_name: web
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - web_dist:/usr/share/nginx/html

  api:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.api
    container_name: api
    restart: unless-stopped
    env_file:
      - ./env/.env

  pocketbase:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.pocketbase
      args:
        PB_VERSION: "0.22.15"  # change as needed
    container_name: pocketbase
    restart: unless-stopped
    volumes:
      - pb_data:/pb/pb_data
      - pb_public:/pb/pb_public
    command: ["/pb/pocketbase", "serve", "--http=0.0.0.0:8090", "--dir=/pb"]

volumes:
  caddy_data: {}
  caddy_config: {}
  web_dist: {}
  pb_data: {}
  pb_public: {}